# Generated by Django 5.2 on 2025-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_phone_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
