# Generated by Django 5.2 on 2025-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_address_resume_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
