# Generated by Django 5.2.3 on 2025-06-25 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
