# Generated by Django 5.2.3 on 2025-06-25 16:03
from django.db import migrations, models
import uuid

def generate_uuids(apps, schema_editor):
    Resume = apps.get_model('resumes', 'Resume')
    for resume in Resume.objects.all():
        resume.public_uuid = uuid.uuid4()
        resume.save()

class Migration(migrations.Migration):
    dependencies = [
        ('resumes', '0006_resume_public_uuid'),
    ]

    operations = [
        migrations.RunPython(generate_uuids),
    ]
