# Generated by Django 5.2.3 on 2025-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_auto_20250625_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('job_ready', 'Job Ready'), ('private', 'Private')], default='draft', max_length=20),
        ),
    ]
