# Generated by Django 5.2.3 on 2025-07-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
